//go:build (all || most || avatica) && !no_avatica

package internal

// Code generated by gen.go. DO NOT EDIT.

import (
	_ "github.com/bongani-m/hardhatdb-cli/drivers/avatica" // Apache Avatica driver
)
