//go:build (all || charts) && !no_charts

package internal

// Code generated by gen.go. DO NOT EDIT.

import (
	_ "github.com/bongani-m/hardhatdb-cli/metacmd/charts/echarts" // ECharts chart renderer
)
