//go:build (!no_base || clickhouse) && !no_clickhouse

package internal

// Code generated by gen.go. DO NOT EDIT.

import (
	_ "github.com/bongani-m/hardhatdb-cli/drivers/clickhouse" // ClickHouse driver
)
