//go:build (!no_base || duckdb) && !no_duckdb && !(linux && arm)

package internal

// Code generated by gen.go. DO NOT EDIT.

import (
	_ "github.com/bongani-m/hardhatdb-cli/drivers/duckdb" // DuckDB driver
)
