//go:build (all || most || firebird) && !no_firebird

package internal

// Code generated by gen.go. DO NOT EDIT.

import (
	_ "github.com/bongani-m/hardhatdb-cli/drivers/firebird" // Firebird driver
)
