//go:build (all || most || flightsql) && !no_flightsql

package internal

// Code generated by gen.go. DO NOT EDIT.

import (
	_ "github.com/bongani-m/hardhatdb-cli/drivers/flightsql" // FlightSQL driver
)
