//go:build (all || most || impala) && !no_impala

package internal

// Code generated by gen.go. DO NOT EDIT.

import (
	_ "github.com/bongani-m/hardhatdb-cli/drivers/impala" // Apache Impala driver
)
