//go:build (all || most || libpq) && !no_libpq

package internal

// Code generated by gen.go. DO NOT EDIT.

import (
	_ "github.com/bongani-m/hardhatdb-cli/drivers/libpq" // PostgreSQL lib/pq driver
)
