//go:build (!no_base || oracle) && !no_oracle && !(linux && arm)

package internal

// Code generated by gen.go. DO NOT EDIT.

import (
	_ "github.com/bongani-m/hardhatdb-cli/drivers/oracle" // Oracle Database driver
)
