//go:build (!no_base || pgx || postgres) && !no_pgx && !no_postgres

package internal

// Code generated by gen.go. DO NOT EDIT.

import (
	_ "github.com/bongani-m/hardhatdb-cli/drivers/pgx" // PostgreSQL PGX driver
)
