//go:build (all || most || surrealdb) && !no_surrealdb

package internal

// Code generated by gen.go. DO NOT EDIT.

import (
	_ "github.com/bongani-m/hardhatdb-cli/drivers/surrealdb" // SurrealDB driver
)
